module.exports = {
  ADD_OR_UPDATE_COMPANY: 'ADD_OR_UPDATE_COMPANY',
  DELETE_COMPANY: 'DELETE_COMPANY',
  ADD_OR_UPDATE_FORM: 'ADD_OR_UPDATE_FORM',
  DELETE_FORM: 'DELETE_FORM',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  GENERATE_PDF: 'GENERATE_PDF',
  GET_FORMS: 'GET_FORMS',
};
