export const FILTER_COMPANIES = 'FILTER_COMPANIES';
export const TOGGLE_PROFILE_MENU = 'TOGGLE_PROFILE_MENU';
export const TOGGLE_SIDEBAR_GROUP = 'TOGGLE_SIDEBAR_GROUP';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SELECT_COMPANY = 'SELECT_COMPANY';
